### ISSUE TITLE
Solution to Bessel functions overflow and undeflow

### ISSUE THREAD

**Issue by pedrohnv** [amaurigmartins/OHLToolbox#4]
Hi! The README calls attention that the Bessel functions may overflow or underflow and an arbitrary precision arithmetic python library is used (mpmath). I suspect that is unnecessary and a native MATLAB solution is possible. Those functions have a third parameter `scale` that computes an exponentially scaled version of them ([see docs for besseli](https://www.mathworks.com/help/matlab/ref/besseli.html?searchHighlight=besseli&s_tid=srchtitle_support_results_1_besseli)). This greatly extends the numerical range that those functions can be used, see the following paper by Vujevic: 

[S. Vujević, D. Lovrić and V. Boras, "High-Accurate Numerical Computation of Internal Impedance of Cylindrical Conductors for Complex Arguments of Arbitrary Magnitude," in IEEE Transactions on Electromagnetic Compatibility, vol. 56, no. 6, pp. 1431-1438, Dec. 2014, doi: 10.1109/TEMC.2014.2352398.](https://ieeexplore.ieee.org/document/6897971)

Overall, the impedance for tubular conductors has a formula with a term of the kind

```
z = (besseli(0, w1) * besselk(1, w2) + besseli(1, w2) * besselk(0, w1)) / (besseli(1, w2) * besselk(1, w1) + besseli(1, w1) * besselk(1, w2))
```

The arguments `w` depend on the frequency `f` and geometry. `w1` is associated with the internal radius and `w2` with the outer radius. We have that

```
limit (f -> oo) w = oo
limit (w -> oo) besseli(n, w) = oo
limit (w -> oo) besselk(n, w) = 0
w1 < w2
```

The scaled version of the modified bessel functions are such that

```
besseli(n, w, 1) = besseli(n, w) * exp(-abs(real(w)))
besselk(n, w, 1) = besselk(n, w) * exp(w)
```

Therefore `z` becomes

```
z = (s1 * besseli(0, w1, 1) * besselk(1, w2, 1) + s2 * besseli(1, w2, 1) * besselk(0, w1, 1)) / (s2 * besseli(1, w2, 1) * besselk(1, w1, 1) + s1 * besseli(1, w1, 1) * besselk(1, w2, 1))
```

where

```
s1 = exp(abs(real(w1)) - w2)
s2 = exp(abs(real(w2)) - w1)
```

Scale factors `s1` and `s2` may still overflow. However, we have

```
limit (w -> oo) s1 = oo
limit (w -> oo) s2 = oo
s1 < s2  because  w1 < w2
limit (w -> oo) s1 / s2 = 0
```

Therefore, we define a `sc` as

```
sc = s1 / s2 = exp(abs(real(w1)) - abs(real(w2)) + w1 - w2)
```
And `z` becomes

```
z = (sc * besseli(0, w1, 1) * besselk(1, w2, 1) + besseli(1, w2, 1) * besselk(0, w1, 1)) / (besseli(1, w2, 1) * besselk(1, w1, 1) + sc * besseli(1, w1, 1) * besselk(1, w2, 1))
```

Note that `sc` may still overlfow, but at a much higher frequency range when compared to the non-scaled version.

**Comment by amaurigmartins** [comment]
Hi Pedro.

Thank you very much for the heads up. This is definitely worth a shot.

I'm working on some stuff for the next release of the toolbox, but after
it's done I will revisit this subject.


Em qua., 3 de jul. de 2024, 10:53, Pedro H. N. Vieira <
***@***.***> escreveu:

**Comment by amaurigmartins** [comment]
Hell yeah, it works!

(Not that I doubted, but I was and still am really proud of the heinous kludge that I pulled through to get this to work in the past.)

Anyway, this solution is much more clean, elegant and MATLABish than my Python duct tape fix. Thanks.
